import test from 'node:test';
import assert from 'node:assert/strict';
import {issuePurchaseActivation,validatePurchaseActivation,finalizePurchaseActivation} from '../functions/activate-member/src/telegram/telegram-purchase-activation.mjs';
const order=()=>({$id:'order-001',kind:'website_order',status:'paid',data:{transaction_id:'tx-001'}});
function fixture(){const db=new Map();return {db,store:{async claim(id,record){if(db.has(id))return null;const row={$id:id,...record,data:JSON.parse(record.payload)};db.set(id,row);return row},async state(id){return db.get(id)||null},async update(table,id,fields){const row=db.get(id);if(!row)throw Error('Missing row');db.set(id,{...row,...fields,data:fields.payload?JSON.parse(fields.payload):row.data})}}}}
test('only settled orders can issue activation',async()=>{const {store}=fixture();for(const status of ['pending','failed','expired','activated'])await assert.rejects(issuePurchaseActivation(store,{...order(),status}),/diverifikasi/)});
test('paid order issues a random unguessable token, stores only fingerprint',async()=>{const {store,db}=fixture(),o=order();const a=await issuePurchaseActivation(store,o);assert.match(a.token,/^[\w-]{43}$/);assert.equal(JSON.stringify([...db.values()]).includes(a.token),false);const r=await validatePurchaseActivation(store,a.token,o);assert.equal(r.order_id,o.$id)});
test('different order cannot redeem token',async()=>{const {store}=fixture(),o=order();const a=await issuePurchaseActivation(store,o);await assert.rejects(validatePurchaseActivation(store,a.token,{...o,$id:'other-order'}),/tidak sah/)});
test('expired token cannot validate',async()=>{const {store}=fixture(),o=order();const a=await issuePurchaseActivation(store,o,{now:100000,ttlMs:60000});await assert.rejects(validatePurchaseActivation(store,a.token,o,{now:160000}),/kedaluwarsa/)});
test('consumed token cannot validate again',async()=>{const {store}=fixture(),o=order();const a=await issuePurchaseActivation(store,o);const r=await validatePurchaseActivation(store,a.token,o);await finalizePurchaseActivation(store,r.activation_id,'123456789');await assert.rejects(validatePurchaseActivation(store,a.token,o),/tidak sah/)});
